### ISSUE TITLE
uninitialized constant BundleCache::AWS

### ISSUE THREAD

**Issue by cjroebuck** [data-axle/bundle_cache#16]
Hey I tried running this on shippable and got the following error:

```
 /home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundle_cache-0.2.2/lib/bundle_cache/install.rb:39:in `rescue in install': uninitialized constant BundleCache::AWS (NameError)
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundle_cache-0.2.2/lib/bundle_cache/install.rb:6:in `install'
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundle_cache-0.2.2/bin/bundle_cache_install:6:in `<top (required)>'
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/bin/bundle_cache_install:23:in `load'
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/bin/bundle_cache_install:23:in `<main>'
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
    from /home/shippable/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
```

Can confirm that all required env variables are correctly set before calling the install script

**Comment by inkstak** [comment]
I've got the same problem. It seems to come from changes in aws-sdk.
You can fix it by forcing its version.

```
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler aws-sdk:1.60.2 bundle_cache
  - bundle_cache_install
```

**Comment by devinhalladay** [comment]
@inkstak Nice catch! That fix worked for me as well.

**Comment by inkstak** [comment]
Since it requires a bundle install & heavy dependencies (nokogiri), I'd prefer using a simple script today.
